sudo: required
services:
  - docker
language: bash
env:
  - radarr_version=0.2.0.1217
script:
# prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
  - docker build --build-arg radarr_version=$radarr_version -t dtroncy/rpi-radarr .
# push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker tag dtroncy/rpi-radarr dtroncy/rpi-radarr:$radarr_version
      travis_wait docker push dtroncy/rpi-radarr:$radarr_version
      docker push dtroncy/rpi-radarr
    fi